[project]
name = "tesi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "matplotlib>=3.10.7",
    "networkx>=3.5",
    "numpy>=2.3.3",
    "python-louvain>=0.16",
    "pyvis>=0.3.2",
    "scipy>=1.16.2",
    "scrapy>=2.13.3",
    "scrapy-playwright>=0.0.44",
    "scrapy-selenium>=0.0.7",
    "selenium>=4.37.0",
    "webdriver-manager>=4.0.2",
]
